FROM circleci/python:3.6.5
MAINTAINER dongxuesen

RUN sudo apt-get update && sudo apt-get install -y libgif-dev libmemcached-dev gettext nginx && sudo apt-get clean

COPY requirements20200213.txt .

RUN pip install --upgrade pip setuptools && \
    pip install -r requirements20200213.txt --timeout=300 && \
    pip uninstall django-jsonfield-hotfix -y && \ 
    pip install django-jsonfield-hotfix==1.3.1.post2
